import { z } from 'zod';
import { apiKeys } from '../../db/schema';
import { createInsertSchema, createSelectSchema } from 'drizzle-zod';

export const apiKeysSchema = createSelectSchema(apiKeys);

export const apiKeysCreateSchema = createInsertSchema(apiKeys, {
    key: z.string().optional(), // Generated by hook or DB default if strictly random
    projectId: z.string().uuid(),
}).omit({
    createdAt: true,
});

export const apiKeysPatchSchema = createInsertSchema(apiKeys).omit({
    createdAt: true,
    projectId: true, // Should not change project
}).partial();
